name: BANDIT
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install bandit
        run: pip install bandit
      - name: Run Banddit
        run: bandit -r -x test ..